name: Puppet lint
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  puppet-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: puppet-lint
      uses: scottbrenner/puppet-lint-action@master
      with:
        args: ./puppetcode/
